FROM golang as builder

ENV GOOS=linux GOARCH=amd64 CGO_ENABLED=0

RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.5.0
# Note, the images must be built for amd64. If the host machine architecture is not amd64
# you will need to cross-compile the binary and move it into /go/bin.
# RUN bash -c 'find /go/bin/${GOOS}_${GOARCH}/ -mindepth 1 -maxdepth 1 -exec mv {} /go/bin \;'

FROM scratch


COPY --from=builder /go/bin /

ENTRYPOINT ["/protoc-gen-openapiv2"]
